### ISSUE TITLE
Blank list item formatting issue in Word

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#204]
```
. {blank}
Basic::: hello
Extended::: hi
```

Will look fine in HTML, but in Word, there will be an empty line between the numbered list item and the definition list item:
```
a)
  Basic        hello
  Extended        hello
```

What we want is this:

```
a)  Basic        hello
     Extended        hello
```

**Comment by opoudjis** [comment]
This is a list in Word that contains a table (which is how we render definition lists in Word, so that they can line up; Word 4 barely understands dl anyway).

Given `<ol><li><table>....`, Word will insert a paragraph break between `<li>` and `<table>`. Word simply cannot embed a table within a list. Seriously. It can't, because a list item is a paragraph in Word, and you can't embed a table within a paragraph. Try it yourself.

You can do behaviour that *sounds* like embedding a table within a paragraph: https://www.techrepublic.com/blog/microsoft-office/tips-for-wrapping-text-around-a-word-table/ . But that is text wrapping around a Word object: it's not embedding, it's text flow trickery, and you really don't want to be doing this here. It will be extremely fragile and uneditable.

Not to mention, I *tried* dragging the table next to the list item. And Word cruelly mocked me, and destroyed the layout of the list it was in, converting it into a table, or shoving the entire list to the right of the table. Dropping a table in the middle of paragraph, and having the paragraph flow around it, is doable; dropping a table at the start of a list item just ends up pushing the list out of the way.

Won't fix. Too hard to be worth it.

**Comment by ronaldtse** [comment]
Yeah, then let's not fix it. In this case we need to explain we cannot display that way, and probably no one should desire to format a document like this either.

**Comment by ronaldtse** [comment]
@opoudjis could you add this to the Guide? Thanks!

**Comment by opoudjis** [comment]
Done
