### ISSUE TITLE
Word: SVG images showing up as blank space in Word Doc

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#226]
It looks like this with a `image::blah.svg[]`.

![screen shot 2018-10-05 at 10 21 28 am](https://user-images.githubusercontent.com/11865/46512854-9c687900-c888-11e8-847c-297708de9816.png)

However if I drag/drop the SVG file (i.e. manually import it via drag/drop), it works:

![screen shot 2018-10-05 at 10 22 29 am](https://user-images.githubusercontent.com/11865/46512855-9e323c80-c888-11e8-9964-b1a891430a52.png)

**Comment by opoudjis** [comment]
Images in Word HTML are imported as  both normal `<img>` tags, and as Microsoft VML statements. 

SVG are not understood by Word HTML: they are imported in Microsoft VML. The `<img>` tag downgrades them to PNG, so Word HTML references both the SVG file, and a converted PNG file.

This means that to render SVG natively, I have to render them as Microsoft VML. Frankly, with VML already deprecated since 1998 (in favour of SVG, in fact), and with the VML fields so opaque, I'd rather not support SVG at all in Word. 

In fact, I think it turns out I can't. I've just done an experiment with the markup: I've saved a document with SVG, and it inserts a link to a PNG image in two places: one, as an alternative to the VML statement if VML is not supported, and one as a VML:imagedata tag. The VML consists of the PNG reference, inside a VML:shape element; the VML:shape also has a MicrosoftOffice:gfxdata attribute, which is Bin64 encoded something. Whatever that something is, it is not SVG: it decodes to a 169KB file, for an SVG original of 15KB (and your accompanying PNG was 41KB; in fact, that's what Word generates too.) When I Bin64-decode the attribute, what I get is not recognised by GraphicConverter as an image. And the only mention of  gfxdata online is how it is undocumented—it's not part of the VML spec, which was W3C, but part of Microsoft's proprietary Office spec.

If I remove the two PNG references, and leave the MicrosoftOffice:gfxdata attribute, then I open the Word document, its image content is blank. Which means the MicrosoftOffice:gfxdata data, whatever the hell it is, is not used to generate an image. 

My conclusion is that Word HTML (which is, after all, a legacy format) is lying about SVG support: what you're seeing if you read Word HTML is not SVG but PNG. And that means that we can't support SVG so long as we use Word HTML. Even if I wanted to, I have no idea what is in 

Native DOCX Word, i.e. OOXML, clearly does support SVG. But you know well that we are in no position to generate OOXML, especially with the level of complexity of our documents.

(And I will not implement OOXML to get SVG to work. That is a nightmare that noone understands, least of all Microsoft themselves as Seb Sauvage pointed out, and few people will notice that it's PNG and not SVG.)
