### ISSUE TITLE
Foreword HTML layout broken

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#240]
See photo of HTML version. This is very strange. Please fix ASAP + release. Thanks.

<img width="950" alt="screen shot 2018-11-08 at 2 34 22 am" src="https://user-images.githubusercontent.com/11865/48184066-da7d1080-e2fe-11e8-83d6-12af9ca0c935.png">

**Comment by opoudjis** [comment]
This has been like this for much of the year, and I've never been able to work out why it is happening. I'll work on this, but I have a merge request from Anton that I need to resolve first. https://github.com/riboseinc/metanorma-iso/pull/239

**Comment by opoudjis** [comment]
This is happening in the Rice document, because the reviewer comment (which is not rendered in HTML) is having its formatting transferred across to the paragraph it annotates. That's the fault of Word HTML being used uncritically in HTML HTML, and me not realising the issue. 

https://github.com/riboseinc/metanorma-iso/issues/123, which was meant to address HTML rendering of annotations, has been left pending for months. I will address the immediate issue by disabling the Word HTML handling of annotation in the normal HTML branch, in isodoc.

**Comment by opoudjis** [comment]
I haven't removed it all, but I've removed the Word HTML setting of annotation containers to be 9pt, which was causing this issue. Fixed in isodoc.
