### ISSUE TITLE
When `:draft:` is not present, do not show "XX Stage"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#241]
When `:draft:` is not present, do not show "XX Stage" (the draft warning is already hidden correctly).

**Comment by opoudjis** [comment]
...!

I'm really surprised to see this. If the document does not clearly indicate it is a draft, and the document becomes available, it will mislead readers about its status. Did this come from ISO secretariat?

**Comment by opoudjis** [comment]
I don't think it is safe to trust users to put in the :draft: attribute

**Comment by ronaldtse** [comment]
Then we turn it around for a `final` attribute?

**Comment by opoudjis** [comment]
This is not the way to handle it. The information about the official status of the document is already indicated in whether the `stage` attribute is either `60` or absent. If it is, then the stage information should be suppressed: a document simply should never have a front page saying "IS stage". Otherwise, whenever a stage has a different value, that information must always appear on the front page, and must not be overridden.

So the actual solution to this is to have the document stage information on the front page of ISO suppressed when the stage is 60.

Please confirm.

**Comment by ronaldtse** [comment]
Confirmed, and this solution has to be portable. 

For example, in CSD any stage before “published” should have the draft warning. 

In ISO, stage 60.00 and 60.60 documents should not have the draft warning.

**Comment by ronaldtse** [comment]
Confirmed, and this solution has to be portable. 

For example, in CSD any stage before “published” should have the draft warning. 

In ISO, stage 60.00 and 60.60 documents should not have the draft warning.

**Comment by opoudjis** [comment]
To make it portable, I am introducing a new metadata attribute: unpublished; its definition will vary for each gem.

**Comment by opoudjis** [comment]
Done for all gems. Will work with next release.
