### ISSUE TITLE
Definition cell alignment with inner EXAMPLE in Word

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-iso#247]
This section is generating the below image in Word, which is somehow misleading since the indent is too much (compared to HTML). Ideally I'd like to have the EXAMPLE align flush with the start of the right cell in Word.

I guess it's a Word problem...

```adoc
. A specific hour and minute
Basic format::: 	["T"][hour][min]
+
[example]
T2320
```

Word:

![screen shot 2019-01-04 at 6 22 04 pm](https://user-images.githubusercontent.com/11865/50683641-b5322780-104d-11e9-98c7-ec6981c06ac8.png)

HTML:
![screen shot 2019-01-04 at 6 26 29 pm](https://user-images.githubusercontent.com/11865/50683811-4acdb700-104e-11e9-9a84-e32da6ec3e97.png)

**Comment by opoudjis** [comment]
As it turns out, the EXAMPLE cell *is* flush-aligned with the right hand cell above it, which you will see if I draw boundaries around the table:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1911039/51555864-8818ae00-1e70-11e9-81db-f69597330945.png">

The real problem is that the EXAMPLE label within the cell is indented. If I undo that, all will be well. (There is no need for the indent, unlike for the HTML, precisely because there is no boundary around the cell.)

**Comment by opoudjis** [comment]
Fixed in isodoc: removed all padding around EXAMPLE label.
